export const VALIDATION_MESSAGE = 'Please, use only string and number symbols';
export const EMPTY_TASK_MESSAGE = 'Please, enter at least one character';
export const REQUIRED_FIELD_MESSAGE = 'Please fill required field';
export const DEADLINE_WARNING = 'Expiration date cannot be less than Creation date'
export const WARNING = 'task-list__input--warning';
export const INVISIBLE = 'display--none';
export const OVERFLOW_HIDDEN = 'overflow--hidden';
export const ACTIVE_LINK = 'filter__btn--active';
export const ENTER_KEY = 13;
export const SORT_DOWN = 'sort_down';
export const SORT_UP = 'sort_up';
export const SORT_TEXT = 'sort_text';
export const SORT_DATE = 'sort_date';
export const FILTER_ALL = 'all';
export const FILTER_ACTIVE = 'active';
export const FILTER_COMPLETED = 'completed'; 
export const SORT_BY_TITLE = 'title';
export const SORT_BY_DATE = 'createDate';
